### ISSUE TITLE
Cannot install on OS X

### ISSUE THREAD

**Issue by howe1rp** [syllog1sm/redshift#19]
Greetings!

I'm really excited to start using this, however I'm not able to install it on my Mac. Here is a link to the message I'm getting: http://pastebin.com/j9cNzdv7. I have followed your installation instructions, but I'm still not able to get it to work. Thanks so much for developing this. I can't wait to get to use it!

**Comment by honnibal** [comment]
Hey,

Try running:

    pip install thinc

Before running:

    pip install -r requirements.txt

I'll amend the instructions if this works for you.

Also, check out http://honnibal.github.io/spaCy/ --- this is the library I've been actively developing. I'll add a note here pointing to that.

**Comment by howe1rp** [comment]
Unfortunately this didn't work, however I was able to install spaCy (thank you very much for the suggestion btw).
